serverConf:
  port: 10000
  bossThread: 1
  workerThread: 2
  idleTimeoutSec: 60
mongoConf:
  mongoConn: "mongodb://127.0.0.1:27017"
  mongoDataBase: game_tutorial
threadPool:
  connect: 2
  logic: 4
  db: 4